---
- name: Copy files to all App servers
  hosts: all
  become: yes
  tasks:
    - name: Copy blog.txt to stapp01
      copy:
        src: /usr/src/devops/blog.txt
        dest: /opt/devops/
        owner: tony
        group: tony
        mode: "0655"
      when: inventory_hostname == "stapp01"

    - name: Copy story.txt to stapp02
      copy:
        src: /usr/src/devops/story.txt
        dest: /opt/devops/
        owner: steve
        group: steve
        mode: "0655"
      when: inventory_hostname == "stapp02"

    - name: Copy media.txt to stapp03
      copy:
        src: /usr/src/devops/media.txt
        dest: /opt/devops/
        owner: banner
        group: banner
        mode: "0655"
      when: inventory_hostname == "stapp03"
...
