---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nautilus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  labels:
     app: httpd
spec:
  volumes:
    - name: storage-devops
      persistentVolumeClaim:
        claimName: pvc-nautilus
  containers:
    - name: container-nautilus
      image: httpd:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: storage-devops
          mountPath:  /usr/local/apache2/htdocs/
---
apiVersion: v1
kind: Service
metadata:
  name: web-nautilus
spec:
   type: NodePort
   selector:
     app: httpd
   ports:
     - port: 80
       targetPort: 80
       nodePort: 30008
