---
- name: Install httpd and add index.html
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present
    - name: Start service httpd
      service:
        name: httpd
        state: started
    - name: Add index.html
      copy:
        dest: /var/www/html/index.html
        content: This is a Nautilus sample file, created using Ansible!
        mode: "0644"
        owner: apache
        group: apache
    - name: Update content in index.html
      lineinfile:
        path: /var/www/html/index.html
        insertbefore: BOF
        line: Welcome to xFusionCorp Industries!
...
