---                                                                                                                                     
- hosts: stapp03
  become: yes                                                                                                                           
  become_user: root                                                                                                                     
  roles:                                                                                                                                
    - role/httpd
